// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qubic/qubic-http/protobuff (interfaces: QubicLiveServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_live_service.go -package=mocks github.com/qubic/qubic-http/protobuff QubicLiveServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	protobuff "github.com/qubic/qubic-http/protobuff"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockQubicLiveServiceClient is a mock of QubicLiveServiceClient interface.
type MockQubicLiveServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockQubicLiveServiceClientMockRecorder
	isgomock struct{}
}

// MockQubicLiveServiceClientMockRecorder is the mock recorder for MockQubicLiveServiceClient.
type MockQubicLiveServiceClientMockRecorder struct {
	mock *MockQubicLiveServiceClient
}

// NewMockQubicLiveServiceClient creates a new mock instance.
func NewMockQubicLiveServiceClient(ctrl *gomock.Controller) *MockQubicLiveServiceClient {
	mock := &MockQubicLiveServiceClient{ctrl: ctrl}
	mock.recorder = &MockQubicLiveServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQubicLiveServiceClient) EXPECT() *MockQubicLiveServiceClientMockRecorder {
	return m.recorder
}

// BroadcastTransaction mocks base method.
func (m *MockQubicLiveServiceClient) BroadcastTransaction(ctx context.Context, in *protobuff.BroadcastTransactionRequest, opts ...grpc.CallOption) (*protobuff.BroadcastTransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BroadcastTransaction", varargs...)
	ret0, _ := ret[0].(*protobuff.BroadcastTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastTransaction indicates an expected call of BroadcastTransaction.
func (mr *MockQubicLiveServiceClientMockRecorder) BroadcastTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTransaction", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).BroadcastTransaction), varargs...)
}

// GetActiveIpos mocks base method.
func (m *MockQubicLiveServiceClient) GetActiveIpos(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protobuff.GetActiveIposResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActiveIpos", varargs...)
	ret0, _ := ret[0].(*protobuff.GetActiveIposResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIpos indicates an expected call of GetActiveIpos.
func (mr *MockQubicLiveServiceClientMockRecorder) GetActiveIpos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIpos", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetActiveIpos), varargs...)
}

// GetBalance mocks base method.
func (m *MockQubicLiveServiceClient) GetBalance(ctx context.Context, in *protobuff.GetBalanceRequest, opts ...grpc.CallOption) (*protobuff.GetBalanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBalance", varargs...)
	ret0, _ := ret[0].(*protobuff.GetBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockQubicLiveServiceClientMockRecorder) GetBalance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetBalance), varargs...)
}

// GetBlockHeight mocks base method.
func (m *MockQubicLiveServiceClient) GetBlockHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protobuff.GetBlockHeightResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockHeight", varargs...)
	ret0, _ := ret[0].(*protobuff.GetBlockHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHeight indicates an expected call of GetBlockHeight.
func (mr *MockQubicLiveServiceClientMockRecorder) GetBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHeight", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetBlockHeight), varargs...)
}

// GetContractIpoBids mocks base method.
func (m *MockQubicLiveServiceClient) GetContractIpoBids(ctx context.Context, in *protobuff.GetContractIpoBidsRequest, opts ...grpc.CallOption) (*protobuff.GetContractIpoBidsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContractIpoBids", varargs...)
	ret0, _ := ret[0].(*protobuff.GetContractIpoBidsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractIpoBids indicates an expected call of GetContractIpoBids.
func (mr *MockQubicLiveServiceClientMockRecorder) GetContractIpoBids(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractIpoBids", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetContractIpoBids), varargs...)
}

// GetIssuedAssetByUniverseIndex mocks base method.
func (m *MockQubicLiveServiceClient) GetIssuedAssetByUniverseIndex(ctx context.Context, in *protobuff.GetByUniverseIndexRequest, opts ...grpc.CallOption) (*protobuff.AssetIssuance, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetIssuedAssetByUniverseIndex", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetIssuance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuedAssetByUniverseIndex indicates an expected call of GetIssuedAssetByUniverseIndex.
func (mr *MockQubicLiveServiceClientMockRecorder) GetIssuedAssetByUniverseIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuedAssetByUniverseIndex", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetIssuedAssetByUniverseIndex), varargs...)
}

// GetIssuedAssets mocks base method.
func (m *MockQubicLiveServiceClient) GetIssuedAssets(ctx context.Context, in *protobuff.IssuedAssetsRequest, opts ...grpc.CallOption) (*protobuff.IssuedAssetsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetIssuedAssets", varargs...)
	ret0, _ := ret[0].(*protobuff.IssuedAssetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuedAssets indicates an expected call of GetIssuedAssets.
func (mr *MockQubicLiveServiceClientMockRecorder) GetIssuedAssets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuedAssets", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetIssuedAssets), varargs...)
}

// GetIssuedAssetsByFilter mocks base method.
func (m *MockQubicLiveServiceClient) GetIssuedAssetsByFilter(ctx context.Context, in *protobuff.GetIssuedAssetsByFilterRequest, opts ...grpc.CallOption) (*protobuff.AssetIssuances, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetIssuedAssetsByFilter", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetIssuances)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuedAssetsByFilter indicates an expected call of GetIssuedAssetsByFilter.
func (mr *MockQubicLiveServiceClientMockRecorder) GetIssuedAssetsByFilter(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuedAssetsByFilter", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetIssuedAssetsByFilter), varargs...)
}

// GetOwnedAssetByUniverseIndex mocks base method.
func (m *MockQubicLiveServiceClient) GetOwnedAssetByUniverseIndex(ctx context.Context, in *protobuff.GetByUniverseIndexRequest, opts ...grpc.CallOption) (*protobuff.AssetOwnership, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOwnedAssetByUniverseIndex", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetOwnership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedAssetByUniverseIndex indicates an expected call of GetOwnedAssetByUniverseIndex.
func (mr *MockQubicLiveServiceClientMockRecorder) GetOwnedAssetByUniverseIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedAssetByUniverseIndex", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetOwnedAssetByUniverseIndex), varargs...)
}

// GetOwnedAssets mocks base method.
func (m *MockQubicLiveServiceClient) GetOwnedAssets(ctx context.Context, in *protobuff.OwnedAssetsRequest, opts ...grpc.CallOption) (*protobuff.OwnedAssetsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOwnedAssets", varargs...)
	ret0, _ := ret[0].(*protobuff.OwnedAssetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedAssets indicates an expected call of GetOwnedAssets.
func (mr *MockQubicLiveServiceClientMockRecorder) GetOwnedAssets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedAssets", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetOwnedAssets), varargs...)
}

// GetOwnedAssetsByFilter mocks base method.
func (m *MockQubicLiveServiceClient) GetOwnedAssetsByFilter(ctx context.Context, in *protobuff.GetOwnedAssetsByFilterRequest, opts ...grpc.CallOption) (*protobuff.AssetOwnerships, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOwnedAssetsByFilter", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetOwnerships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedAssetsByFilter indicates an expected call of GetOwnedAssetsByFilter.
func (mr *MockQubicLiveServiceClientMockRecorder) GetOwnedAssetsByFilter(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedAssetsByFilter", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetOwnedAssetsByFilter), varargs...)
}

// GetPossessedAssetByUniverseIndex mocks base method.
func (m *MockQubicLiveServiceClient) GetPossessedAssetByUniverseIndex(ctx context.Context, in *protobuff.GetByUniverseIndexRequest, opts ...grpc.CallOption) (*protobuff.AssetPossession, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPossessedAssetByUniverseIndex", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetPossession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPossessedAssetByUniverseIndex indicates an expected call of GetPossessedAssetByUniverseIndex.
func (mr *MockQubicLiveServiceClientMockRecorder) GetPossessedAssetByUniverseIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPossessedAssetByUniverseIndex", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetPossessedAssetByUniverseIndex), varargs...)
}

// GetPossessedAssets mocks base method.
func (m *MockQubicLiveServiceClient) GetPossessedAssets(ctx context.Context, in *protobuff.PossessedAssetsRequest, opts ...grpc.CallOption) (*protobuff.PossessedAssetsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPossessedAssets", varargs...)
	ret0, _ := ret[0].(*protobuff.PossessedAssetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPossessedAssets indicates an expected call of GetPossessedAssets.
func (mr *MockQubicLiveServiceClientMockRecorder) GetPossessedAssets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPossessedAssets", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetPossessedAssets), varargs...)
}

// GetPossessedAssetsByFilter mocks base method.
func (m *MockQubicLiveServiceClient) GetPossessedAssetsByFilter(ctx context.Context, in *protobuff.GetPossessedAssetsByFilterRequest, opts ...grpc.CallOption) (*protobuff.AssetPossessions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPossessedAssetsByFilter", varargs...)
	ret0, _ := ret[0].(*protobuff.AssetPossessions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPossessedAssetsByFilter indicates an expected call of GetPossessedAssetsByFilter.
func (mr *MockQubicLiveServiceClientMockRecorder) GetPossessedAssetsByFilter(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPossessedAssetsByFilter", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetPossessedAssetsByFilter), varargs...)
}

// GetTickInfo mocks base method.
func (m *MockQubicLiveServiceClient) GetTickInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protobuff.GetTickInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTickInfo", varargs...)
	ret0, _ := ret[0].(*protobuff.GetTickInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickInfo indicates an expected call of GetTickInfo.
func (mr *MockQubicLiveServiceClientMockRecorder) GetTickInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickInfo", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).GetTickInfo), varargs...)
}

// QuerySmartContract mocks base method.
func (m *MockQubicLiveServiceClient) QuerySmartContract(ctx context.Context, in *protobuff.QuerySmartContractRequest, opts ...grpc.CallOption) (*protobuff.QuerySmartContractResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QuerySmartContract", varargs...)
	ret0, _ := ret[0].(*protobuff.QuerySmartContractResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySmartContract indicates an expected call of QuerySmartContract.
func (mr *MockQubicLiveServiceClientMockRecorder) QuerySmartContract(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySmartContract", reflect.TypeOf((*MockQubicLiveServiceClient)(nil).QuerySmartContract), varargs...)
}
