// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qubic/aggregation/ipo/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpoBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpoBid) Reset() {
	*x = IpoBid{}
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpoBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpoBid) ProtoMessage() {}

func (x *IpoBid) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpoBid.ProtoReflect.Descriptor instead.
func (*IpoBid) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *IpoBid) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *IpoBid) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BidTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	TickNumber    uint32                 `protobuf:"varint,5,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InputType     uint32                 `protobuf:"varint,7,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputSize     uint32                 `protobuf:"varint,8,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	InputData     string                 `protobuf:"bytes,9,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Signature     string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	MoneyFlew     bool                   `protobuf:"varint,11,opt,name=money_flew,json=moneyFlew,proto3" json:"money_flew,omitempty"`
	Bid           *IpoBid                `protobuf:"bytes,12,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidTransaction) Reset() {
	*x = BidTransaction{}
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidTransaction) ProtoMessage() {}

func (x *BidTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidTransaction.ProtoReflect.Descriptor instead.
func (*BidTransaction) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BidTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BidTransaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BidTransaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BidTransaction) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *BidTransaction) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *BidTransaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidTransaction) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *BidTransaction) GetInputSize() uint32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *BidTransaction) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *BidTransaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BidTransaction) GetMoneyFlew() bool {
	if x != nil {
		return x.MoneyFlew
	}
	return false
}

func (x *BidTransaction) GetBid() *IpoBid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type IpoBidTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetName       string                 `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	ContractIndex   uint32                 `protobuf:"varint,2,opt,name=contract_index,json=contractIndex,proto3" json:"contract_index,omitempty"`
	ContractAddress string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Transactions    []*BidTransaction      `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IpoBidTransactions) Reset() {
	*x = IpoBidTransactions{}
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpoBidTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpoBidTransactions) ProtoMessage() {}

func (x *IpoBidTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpoBidTransactions.ProtoReflect.Descriptor instead.
func (*IpoBidTransactions) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *IpoBidTransactions) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *IpoBidTransactions) GetContractIndex() uint32 {
	if x != nil {
		return x.ContractIndex
	}
	return 0
}

func (x *IpoBidTransactions) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IpoBidTransactions) GetTransactions() []*BidTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetCurrentIpoBidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []string               `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentIpoBidsRequest) Reset() {
	*x = GetCurrentIpoBidsRequest{}
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentIpoBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIpoBidsRequest) ProtoMessage() {}

func (x *GetCurrentIpoBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIpoBidsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentIpoBidsRequest) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentIpoBidsRequest) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type GetCurrentIpoBidsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IpoTransactions []*IpoBidTransactions  `protobuf:"bytes,1,rep,name=ipo_transactions,json=ipoTransactions,proto3" json:"ipo_transactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCurrentIpoBidsResponse) Reset() {
	*x = GetCurrentIpoBidsResponse{}
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentIpoBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIpoBidsResponse) ProtoMessage() {}

func (x *GetCurrentIpoBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_ipo_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIpoBidsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentIpoBidsResponse) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentIpoBidsResponse) GetIpoTransactions() []*IpoBidTransactions {
	if x != nil {
		return x.IpoTransactions
	}
	return nil
}

var File_qubic_aggregation_ipo_v1_messages_proto protoreflect.FileDescriptor

const file_qubic_aggregation_ipo_v1_messages_proto_rawDesc = "" +
	"\n" +
	"'qubic/aggregation/ipo/v1/messages.proto\x12\x18qubic.aggregation.ipo.v1\":\n" +
	"\x06IpoBid\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\x83\x03\n" +
	"\x0eBidTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1f\n" +
	"\vtick_number\x18\x05 \x01(\rR\n" +
	"tickNumber\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"input_type\x18\a \x01(\rR\tinputType\x12\x1d\n" +
	"\n" +
	"input_size\x18\b \x01(\rR\tinputSize\x12\x1d\n" +
	"\n" +
	"input_data\x18\t \x01(\tR\tinputData\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"money_flew\x18\v \x01(\bR\tmoneyFlew\x122\n" +
	"\x03bid\x18\f \x01(\v2 .qubic.aggregation.ipo.v1.IpoBidR\x03bid\"\xd3\x01\n" +
	"\x12IpoBidTransactions\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\tR\tassetName\x12%\n" +
	"\x0econtract_index\x18\x02 \x01(\rR\rcontractIndex\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\x12L\n" +
	"\ftransactions\x18\x04 \x03(\v2(.qubic.aggregation.ipo.v1.BidTransactionR\ftransactions\":\n" +
	"\x18GetCurrentIpoBidsRequest\x12\x1e\n" +
	"\n" +
	"identities\x18\x01 \x03(\tR\n" +
	"identities\"t\n" +
	"\x19GetCurrentIpoBidsResponse\x12W\n" +
	"\x10ipo_transactions\x18\x01 \x03(\v2,.qubic.aggregation.ipo.v1.IpoBidTransactionsR\x0fipoTransactionsB;Z9github.com/qubic/qubic-aggregation/ipo-service/api/ipo/v1b\x06proto3"

var (
	file_qubic_aggregation_ipo_v1_messages_proto_rawDescOnce sync.Once
	file_qubic_aggregation_ipo_v1_messages_proto_rawDescData []byte
)

func file_qubic_aggregation_ipo_v1_messages_proto_rawDescGZIP() []byte {
	file_qubic_aggregation_ipo_v1_messages_proto_rawDescOnce.Do(func() {
		file_qubic_aggregation_ipo_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qubic_aggregation_ipo_v1_messages_proto_rawDesc), len(file_qubic_aggregation_ipo_v1_messages_proto_rawDesc)))
	})
	return file_qubic_aggregation_ipo_v1_messages_proto_rawDescData
}

var file_qubic_aggregation_ipo_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_qubic_aggregation_ipo_v1_messages_proto_goTypes = []any{
	(*IpoBid)(nil),                    // 0: qubic.aggregation.ipo.v1.IpoBid
	(*BidTransaction)(nil),            // 1: qubic.aggregation.ipo.v1.BidTransaction
	(*IpoBidTransactions)(nil),        // 2: qubic.aggregation.ipo.v1.IpoBidTransactions
	(*GetCurrentIpoBidsRequest)(nil),  // 3: qubic.aggregation.ipo.v1.GetCurrentIpoBidsRequest
	(*GetCurrentIpoBidsResponse)(nil), // 4: qubic.aggregation.ipo.v1.GetCurrentIpoBidsResponse
}
var file_qubic_aggregation_ipo_v1_messages_proto_depIdxs = []int32{
	0, // 0: qubic.aggregation.ipo.v1.BidTransaction.bid:type_name -> qubic.aggregation.ipo.v1.IpoBid
	1, // 1: qubic.aggregation.ipo.v1.IpoBidTransactions.transactions:type_name -> qubic.aggregation.ipo.v1.BidTransaction
	2, // 2: qubic.aggregation.ipo.v1.GetCurrentIpoBidsResponse.ipo_transactions:type_name -> qubic.aggregation.ipo.v1.IpoBidTransactions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_qubic_aggregation_ipo_v1_messages_proto_init() }
func file_qubic_aggregation_ipo_v1_messages_proto_init() {
	if File_qubic_aggregation_ipo_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qubic_aggregation_ipo_v1_messages_proto_rawDesc), len(file_qubic_aggregation_ipo_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qubic_aggregation_ipo_v1_messages_proto_goTypes,
		DependencyIndexes: file_qubic_aggregation_ipo_v1_messages_proto_depIdxs,
		MessageInfos:      file_qubic_aggregation_ipo_v1_messages_proto_msgTypes,
	}.Build()
	File_qubic_aggregation_ipo_v1_messages_proto = out.File
	file_qubic_aggregation_ipo_v1_messages_proto_goTypes = nil
	file_qubic_aggregation_ipo_v1_messages_proto_depIdxs = nil
}
