// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qubic/aggregation/ipo/v1/service.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_qubic_aggregation_ipo_v1_service_proto protoreflect.FileDescriptor

const file_qubic_aggregation_ipo_v1_service_proto_rawDesc = "" +
	"\n" +
	"&qubic/aggregation/ipo/v1/service.proto\x12\x18qubic.aggregation.ipo.v1\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a'qubic/aggregation/ipo/v1/messages.proto2\xfd\x02\n" +
	"\x15AggregationIpoService\x12\xe3\x02\n" +
	"\x11GetCurrentIpoBids\x122.qubic.aggregation.ipo.v1.GetCurrentIpoBidsRequest\x1a3.qubic.aggregation.ipo.v1.GetCurrentIpoBidsResponse\"\xe4\x01\xbaG\xb1\x01\x126Get bidder bid transactions for currently active IPOs.\x1awAllows for requesting the transactions associated with bids of currently active IPOs for a number of bidder identities.\x82\xd3\xe4\x93\x02):\x01*b\x10ipo_transactions\"\x12/getCurrentIpoBidsB\xf5\x01\xbaG\xb6\x01\x12i\n" +
	"\x1dQubic IPO Aggregation Service\x12AAPI for querying transactions related to smart contract IPO bids.2\x051.0.0\x1a\x13\n" +
	"\x11https://TO-DEFINEB4\n" +
	"\x06GitHub\x12*https://github.com/qubic/qubic-aggregationZ9github.com/qubic/qubic-aggregation/ipo-service/api/ipo/v1b\x06proto3"

var file_qubic_aggregation_ipo_v1_service_proto_goTypes = []any{
	(*GetCurrentIpoBidsRequest)(nil),  // 0: qubic.aggregation.ipo.v1.GetCurrentIpoBidsRequest
	(*GetCurrentIpoBidsResponse)(nil), // 1: qubic.aggregation.ipo.v1.GetCurrentIpoBidsResponse
}
var file_qubic_aggregation_ipo_v1_service_proto_depIdxs = []int32{
	0, // 0: qubic.aggregation.ipo.v1.AggregationIpoService.GetCurrentIpoBids:input_type -> qubic.aggregation.ipo.v1.GetCurrentIpoBidsRequest
	1, // 1: qubic.aggregation.ipo.v1.AggregationIpoService.GetCurrentIpoBids:output_type -> qubic.aggregation.ipo.v1.GetCurrentIpoBidsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qubic_aggregation_ipo_v1_service_proto_init() }
func file_qubic_aggregation_ipo_v1_service_proto_init() {
	if File_qubic_aggregation_ipo_v1_service_proto != nil {
		return
	}
	file_qubic_aggregation_ipo_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qubic_aggregation_ipo_v1_service_proto_rawDesc), len(file_qubic_aggregation_ipo_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qubic_aggregation_ipo_v1_service_proto_goTypes,
		DependencyIndexes: file_qubic_aggregation_ipo_v1_service_proto_depIdxs,
	}.Build()
	File_qubic_aggregation_ipo_v1_service_proto = out.File
	file_qubic_aggregation_ipo_v1_service_proto_goTypes = nil
	file_qubic_aggregation_ipo_v1_service_proto_depIdxs = nil
}
