// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: qubic/aggregation/ipo/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregationIpoService_GetCurrentIpoBids_FullMethodName = "/qubic.aggregation.ipo.v1.AggregationIpoService/GetCurrentIpoBids"
)

// AggregationIpoServiceClient is the client API for AggregationIpoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregationIpoServiceClient interface {
	GetCurrentIpoBids(ctx context.Context, in *GetCurrentIpoBidsRequest, opts ...grpc.CallOption) (*GetCurrentIpoBidsResponse, error)
}

type aggregationIpoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregationIpoServiceClient(cc grpc.ClientConnInterface) AggregationIpoServiceClient {
	return &aggregationIpoServiceClient{cc}
}

func (c *aggregationIpoServiceClient) GetCurrentIpoBids(ctx context.Context, in *GetCurrentIpoBidsRequest, opts ...grpc.CallOption) (*GetCurrentIpoBidsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentIpoBidsResponse)
	err := c.cc.Invoke(ctx, AggregationIpoService_GetCurrentIpoBids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregationIpoServiceServer is the server API for AggregationIpoService service.
// All implementations must embed UnimplementedAggregationIpoServiceServer
// for forward compatibility.
type AggregationIpoServiceServer interface {
	GetCurrentIpoBids(context.Context, *GetCurrentIpoBidsRequest) (*GetCurrentIpoBidsResponse, error)
	mustEmbedUnimplementedAggregationIpoServiceServer()
}

// UnimplementedAggregationIpoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregationIpoServiceServer struct{}

func (UnimplementedAggregationIpoServiceServer) GetCurrentIpoBids(context.Context, *GetCurrentIpoBidsRequest) (*GetCurrentIpoBidsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentIpoBids not implemented")
}
func (UnimplementedAggregationIpoServiceServer) mustEmbedUnimplementedAggregationIpoServiceServer() {}
func (UnimplementedAggregationIpoServiceServer) testEmbeddedByValue()                               {}

// UnsafeAggregationIpoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregationIpoServiceServer will
// result in compilation errors.
type UnsafeAggregationIpoServiceServer interface {
	mustEmbedUnimplementedAggregationIpoServiceServer()
}

func RegisterAggregationIpoServiceServer(s grpc.ServiceRegistrar, srv AggregationIpoServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregationIpoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregationIpoService_ServiceDesc, srv)
}

func _AggregationIpoService_GetCurrentIpoBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentIpoBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationIpoServiceServer).GetCurrentIpoBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationIpoService_GetCurrentIpoBids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationIpoServiceServer).GetCurrentIpoBids(ctx, req.(*GetCurrentIpoBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregationIpoService_ServiceDesc is the grpc.ServiceDesc for AggregationIpoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregationIpoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.aggregation.ipo.v1.AggregationIpoService",
	HandlerType: (*AggregationIpoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentIpoBids",
			Handler:    _AggregationIpoService_GetCurrentIpoBids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qubic/aggregation/ipo/v1/service.proto",
}
