// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qubic/qubic-aggregation/ipo-service/domain (interfaces: LiveService,StatusService,QueryService,BidServicer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_interfaces.go -package=mocks github.com/qubic/qubic-aggregation/ipo-service/domain LiveService,StatusService,QueryService,BidServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/qubic/qubic-aggregation/ipo-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLiveService is a mock of LiveService interface.
type MockLiveService struct {
	ctrl     *gomock.Controller
	recorder *MockLiveServiceMockRecorder
	isgomock struct{}
}

// MockLiveServiceMockRecorder is the mock recorder for MockLiveService.
type MockLiveServiceMockRecorder struct {
	mock *MockLiveService
}

// NewMockLiveService creates a new mock instance.
func NewMockLiveService(ctrl *gomock.Controller) *MockLiveService {
	mock := &MockLiveService{ctrl: ctrl}
	mock.recorder = &MockLiveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveService) EXPECT() *MockLiveServiceMockRecorder {
	return m.recorder
}

// GetActiveIpos mocks base method.
func (m *MockLiveService) GetActiveIpos(ctx context.Context) ([]domain.Ipo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveIpos", ctx)
	ret0, _ := ret[0].([]domain.Ipo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIpos indicates an expected call of GetActiveIpos.
func (mr *MockLiveServiceMockRecorder) GetActiveIpos(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIpos", reflect.TypeOf((*MockLiveService)(nil).GetActiveIpos), ctx)
}

// GetContractIpoBids mocks base method.
func (m *MockLiveService) GetContractIpoBids(ctx context.Context, contractIndex uint32) (domain.IpoBidData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractIpoBids", ctx, contractIndex)
	ret0, _ := ret[0].(domain.IpoBidData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractIpoBids indicates an expected call of GetContractIpoBids.
func (mr *MockLiveServiceMockRecorder) GetContractIpoBids(ctx, contractIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractIpoBids", reflect.TypeOf((*MockLiveService)(nil).GetContractIpoBids), ctx, contractIndex)
}

// GetTickInfo mocks base method.
func (m *MockLiveService) GetTickInfo(ctx context.Context) (domain.TickInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickInfo", ctx)
	ret0, _ := ret[0].(domain.TickInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickInfo indicates an expected call of GetTickInfo.
func (mr *MockLiveServiceMockRecorder) GetTickInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickInfo", reflect.TypeOf((*MockLiveService)(nil).GetTickInfo), ctx)
}

// MockStatusService is a mock of StatusService interface.
type MockStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockStatusServiceMockRecorder
	isgomock struct{}
}

// MockStatusServiceMockRecorder is the mock recorder for MockStatusService.
type MockStatusServiceMockRecorder struct {
	mock *MockStatusService
}

// NewMockStatusService creates a new mock instance.
func NewMockStatusService(ctrl *gomock.Controller) *MockStatusService {
	mock := &MockStatusService{ctrl: ctrl}
	mock.recorder = &MockStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusService) EXPECT() *MockStatusServiceMockRecorder {
	return m.recorder
}

// GetTickIntervals mocks base method.
func (m *MockStatusService) GetTickIntervals(ctx context.Context) (map[uint32][]domain.TickInterval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickIntervals", ctx)
	ret0, _ := ret[0].(map[uint32][]domain.TickInterval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickIntervals indicates an expected call of GetTickIntervals.
func (mr *MockStatusServiceMockRecorder) GetTickIntervals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickIntervals", reflect.TypeOf((*MockStatusService)(nil).GetTickIntervals), ctx)
}

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// GetIPOBidTransactionsForIdentity mocks base method.
func (m *MockQueryService) GetIPOBidTransactionsForIdentity(ctx context.Context, identity, destination string, tickInterval domain.TickInterval) ([]domain.BidTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPOBidTransactionsForIdentity", ctx, identity, destination, tickInterval)
	ret0, _ := ret[0].([]domain.BidTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPOBidTransactionsForIdentity indicates an expected call of GetIPOBidTransactionsForIdentity.
func (mr *MockQueryServiceMockRecorder) GetIPOBidTransactionsForIdentity(ctx, identity, destination, tickInterval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPOBidTransactionsForIdentity", reflect.TypeOf((*MockQueryService)(nil).GetIPOBidTransactionsForIdentity), ctx, identity, destination, tickInterval)
}

// MockBidServicer is a mock of BidServicer interface.
type MockBidServicer struct {
	ctrl     *gomock.Controller
	recorder *MockBidServicerMockRecorder
	isgomock struct{}
}

// MockBidServicerMockRecorder is the mock recorder for MockBidServicer.
type MockBidServicerMockRecorder struct {
	mock *MockBidServicer
}

// NewMockBidServicer creates a new mock instance.
func NewMockBidServicer(ctrl *gomock.Controller) *MockBidServicer {
	mock := &MockBidServicer{ctrl: ctrl}
	mock.recorder = &MockBidServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBidServicer) EXPECT() *MockBidServicerMockRecorder {
	return m.recorder
}

// GetCurrentIPOBidTransactions mocks base method.
func (m *MockBidServicer) GetCurrentIPOBidTransactions(ctx context.Context, identities []string) ([]domain.IpoBidTransactions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentIPOBidTransactions", ctx, identities)
	ret0, _ := ret[0].([]domain.IpoBidTransactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentIPOBidTransactions indicates an expected call of GetCurrentIPOBidTransactions.
func (mr *MockBidServicerMockRecorder) GetCurrentIPOBidTransactions(ctx, identities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentIPOBidTransactions", reflect.TypeOf((*MockBidServicer)(nil).GetCurrentIPOBidTransactions), ctx, identities)
}
