// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qubic/aggregation/general/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpoBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpoBid) Reset() {
	*x = IpoBid{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpoBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpoBid) ProtoMessage() {}

func (x *IpoBid) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpoBid.ProtoReflect.Descriptor instead.
func (*IpoBid) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *IpoBid) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *IpoBid) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BidTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	TickNumber    uint32                 `protobuf:"varint,5,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InputType     uint32                 `protobuf:"varint,7,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputSize     uint32                 `protobuf:"varint,8,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	InputData     string                 `protobuf:"bytes,9,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Signature     string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	MoneyFlew     bool                   `protobuf:"varint,11,opt,name=money_flew,json=moneyFlew,proto3" json:"money_flew,omitempty"`
	Bid           *IpoBid                `protobuf:"bytes,12,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidTransaction) Reset() {
	*x = BidTransaction{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidTransaction) ProtoMessage() {}

func (x *BidTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidTransaction.ProtoReflect.Descriptor instead.
func (*BidTransaction) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BidTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BidTransaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BidTransaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BidTransaction) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *BidTransaction) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *BidTransaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidTransaction) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *BidTransaction) GetInputSize() uint32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *BidTransaction) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *BidTransaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BidTransaction) GetMoneyFlew() bool {
	if x != nil {
		return x.MoneyFlew
	}
	return false
}

func (x *BidTransaction) GetBid() *IpoBid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type IpoBidTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetName       string                 `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	ContractIndex   uint32                 `protobuf:"varint,2,opt,name=contract_index,json=contractIndex,proto3" json:"contract_index,omitempty"`
	ContractAddress string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Transactions    []*BidTransaction      `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IpoBidTransactions) Reset() {
	*x = IpoBidTransactions{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpoBidTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpoBidTransactions) ProtoMessage() {}

func (x *IpoBidTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpoBidTransactions.ProtoReflect.Descriptor instead.
func (*IpoBidTransactions) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *IpoBidTransactions) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *IpoBidTransactions) GetContractIndex() uint32 {
	if x != nil {
		return x.ContractIndex
	}
	return 0
}

func (x *IpoBidTransactions) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IpoBidTransactions) GetTransactions() []*BidTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetCurrentIpoBidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []string               `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentIpoBidsRequest) Reset() {
	*x = GetCurrentIpoBidsRequest{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentIpoBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIpoBidsRequest) ProtoMessage() {}

func (x *GetCurrentIpoBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIpoBidsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentIpoBidsRequest) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentIpoBidsRequest) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type GetCurrentIpoBidsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IpoTransactions []*IpoBidTransactions  `protobuf:"bytes,1,rep,name=ipo_transactions,json=ipoTransactions,proto3" json:"ipo_transactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCurrentIpoBidsResponse) Reset() {
	*x = GetCurrentIpoBidsResponse{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentIpoBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIpoBidsResponse) ProtoMessage() {}

func (x *GetCurrentIpoBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIpoBidsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentIpoBidsResponse) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentIpoBidsResponse) GetIpoTransactions() []*IpoBidTransactions {
	if x != nil {
		return x.IpoTransactions
	}
	return nil
}

type IdentityBalance struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance                    int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ValidForTick               uint32                 `protobuf:"varint,3,opt,name=valid_for_tick,json=validForTick,proto3" json:"valid_for_tick,omitempty"`
	LatestIncomingTransferTick uint32                 `protobuf:"varint,4,opt,name=latest_incoming_transfer_tick,json=latestIncomingTransferTick,proto3" json:"latest_incoming_transfer_tick,omitempty"`
	LatestOutgoingTransferTick uint32                 `protobuf:"varint,5,opt,name=latest_outgoing_transfer_tick,json=latestOutgoingTransferTick,proto3" json:"latest_outgoing_transfer_tick,omitempty"`
	IncomingAmount             int64                  `protobuf:"varint,6,opt,name=incoming_amount,json=incomingAmount,proto3" json:"incoming_amount,omitempty"`
	OutgoingAmount             int64                  `protobuf:"varint,7,opt,name=outgoing_amount,json=outgoingAmount,proto3" json:"outgoing_amount,omitempty"`
	NumberOfIncomingTransfers  uint32                 `protobuf:"varint,8,opt,name=number_of_incoming_transfers,json=numberOfIncomingTransfers,proto3" json:"number_of_incoming_transfers,omitempty"`
	NumberOfOutgoingTransfers  uint32                 `protobuf:"varint,9,opt,name=number_of_outgoing_transfers,json=numberOfOutgoingTransfers,proto3" json:"number_of_outgoing_transfers,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *IdentityBalance) Reset() {
	*x = IdentityBalance{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityBalance) ProtoMessage() {}

func (x *IdentityBalance) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityBalance.ProtoReflect.Descriptor instead.
func (*IdentityBalance) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityBalance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityBalance) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *IdentityBalance) GetValidForTick() uint32 {
	if x != nil {
		return x.ValidForTick
	}
	return 0
}

func (x *IdentityBalance) GetLatestIncomingTransferTick() uint32 {
	if x != nil {
		return x.LatestIncomingTransferTick
	}
	return 0
}

func (x *IdentityBalance) GetLatestOutgoingTransferTick() uint32 {
	if x != nil {
		return x.LatestOutgoingTransferTick
	}
	return 0
}

func (x *IdentityBalance) GetIncomingAmount() int64 {
	if x != nil {
		return x.IncomingAmount
	}
	return 0
}

func (x *IdentityBalance) GetOutgoingAmount() int64 {
	if x != nil {
		return x.OutgoingAmount
	}
	return 0
}

func (x *IdentityBalance) GetNumberOfIncomingTransfers() uint32 {
	if x != nil {
		return x.NumberOfIncomingTransfers
	}
	return 0
}

func (x *IdentityBalance) GetNumberOfOutgoingTransfers() uint32 {
	if x != nil {
		return x.NumberOfOutgoingTransfers
	}
	return 0
}

type GetIdentitiesBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []string               `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentitiesBalancesRequest) Reset() {
	*x = GetIdentitiesBalancesRequest{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentitiesBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentitiesBalancesRequest) ProtoMessage() {}

func (x *GetIdentitiesBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentitiesBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetIdentitiesBalancesRequest) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdentitiesBalancesRequest) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type GetIdentitiesBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*IdentityBalance     `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentitiesBalancesResponse) Reset() {
	*x = GetIdentitiesBalancesResponse{}
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentitiesBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentitiesBalancesResponse) ProtoMessage() {}

func (x *GetIdentitiesBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_aggregation_general_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentitiesBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetIdentitiesBalancesResponse) Descriptor() ([]byte, []int) {
	return file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetIdentitiesBalancesResponse) GetBalances() []*IdentityBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

var File_qubic_aggregation_general_v1_messages_proto protoreflect.FileDescriptor

const file_qubic_aggregation_general_v1_messages_proto_rawDesc = "" +
	"\n" +
	"+qubic/aggregation/general/v1/messages.proto\x12\x1cqubic.aggregation.general.v1\":\n" +
	"\x06IpoBid\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\x87\x03\n" +
	"\x0eBidTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1f\n" +
	"\vtick_number\x18\x05 \x01(\rR\n" +
	"tickNumber\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"input_type\x18\a \x01(\rR\tinputType\x12\x1d\n" +
	"\n" +
	"input_size\x18\b \x01(\rR\tinputSize\x12\x1d\n" +
	"\n" +
	"input_data\x18\t \x01(\tR\tinputData\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"money_flew\x18\v \x01(\bR\tmoneyFlew\x126\n" +
	"\x03bid\x18\f \x01(\v2$.qubic.aggregation.general.v1.IpoBidR\x03bid\"\xd7\x01\n" +
	"\x12IpoBidTransactions\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\tR\tassetName\x12%\n" +
	"\x0econtract_index\x18\x02 \x01(\rR\rcontractIndex\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\x12P\n" +
	"\ftransactions\x18\x04 \x03(\v2,.qubic.aggregation.general.v1.BidTransactionR\ftransactions\":\n" +
	"\x18GetCurrentIpoBidsRequest\x12\x1e\n" +
	"\n" +
	"identities\x18\x01 \x03(\tR\n" +
	"identities\"x\n" +
	"\x19GetCurrentIpoBidsResponse\x12[\n" +
	"\x10ipo_transactions\x18\x01 \x03(\v20.qubic.aggregation.general.v1.IpoBidTransactionsR\x0fipoTransactions\"\xbb\x03\n" +
	"\x0fIdentityBalance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12$\n" +
	"\x0evalid_for_tick\x18\x03 \x01(\rR\fvalidForTick\x12A\n" +
	"\x1dlatest_incoming_transfer_tick\x18\x04 \x01(\rR\x1alatestIncomingTransferTick\x12A\n" +
	"\x1dlatest_outgoing_transfer_tick\x18\x05 \x01(\rR\x1alatestOutgoingTransferTick\x12'\n" +
	"\x0fincoming_amount\x18\x06 \x01(\x03R\x0eincomingAmount\x12'\n" +
	"\x0foutgoing_amount\x18\a \x01(\x03R\x0eoutgoingAmount\x12?\n" +
	"\x1cnumber_of_incoming_transfers\x18\b \x01(\rR\x19numberOfIncomingTransfers\x12?\n" +
	"\x1cnumber_of_outgoing_transfers\x18\t \x01(\rR\x19numberOfOutgoingTransfers\">\n" +
	"\x1cGetIdentitiesBalancesRequest\x12\x1e\n" +
	"\n" +
	"identities\x18\x01 \x03(\tR\n" +
	"identities\"j\n" +
	"\x1dGetIdentitiesBalancesResponse\x12I\n" +
	"\bbalances\x18\x01 \x03(\v2-.qubic.aggregation.general.v1.IdentityBalanceR\bbalancesBCZAgithub.com/qubic/qubic-aggregation/general-service/api/general/v1b\x06proto3"

var (
	file_qubic_aggregation_general_v1_messages_proto_rawDescOnce sync.Once
	file_qubic_aggregation_general_v1_messages_proto_rawDescData []byte
)

func file_qubic_aggregation_general_v1_messages_proto_rawDescGZIP() []byte {
	file_qubic_aggregation_general_v1_messages_proto_rawDescOnce.Do(func() {
		file_qubic_aggregation_general_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qubic_aggregation_general_v1_messages_proto_rawDesc), len(file_qubic_aggregation_general_v1_messages_proto_rawDesc)))
	})
	return file_qubic_aggregation_general_v1_messages_proto_rawDescData
}

var file_qubic_aggregation_general_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_qubic_aggregation_general_v1_messages_proto_goTypes = []any{
	(*IpoBid)(nil),                        // 0: qubic.aggregation.general.v1.IpoBid
	(*BidTransaction)(nil),                // 1: qubic.aggregation.general.v1.BidTransaction
	(*IpoBidTransactions)(nil),            // 2: qubic.aggregation.general.v1.IpoBidTransactions
	(*GetCurrentIpoBidsRequest)(nil),      // 3: qubic.aggregation.general.v1.GetCurrentIpoBidsRequest
	(*GetCurrentIpoBidsResponse)(nil),     // 4: qubic.aggregation.general.v1.GetCurrentIpoBidsResponse
	(*IdentityBalance)(nil),               // 5: qubic.aggregation.general.v1.IdentityBalance
	(*GetIdentitiesBalancesRequest)(nil),  // 6: qubic.aggregation.general.v1.GetIdentitiesBalancesRequest
	(*GetIdentitiesBalancesResponse)(nil), // 7: qubic.aggregation.general.v1.GetIdentitiesBalancesResponse
}
var file_qubic_aggregation_general_v1_messages_proto_depIdxs = []int32{
	0, // 0: qubic.aggregation.general.v1.BidTransaction.bid:type_name -> qubic.aggregation.general.v1.IpoBid
	1, // 1: qubic.aggregation.general.v1.IpoBidTransactions.transactions:type_name -> qubic.aggregation.general.v1.BidTransaction
	2, // 2: qubic.aggregation.general.v1.GetCurrentIpoBidsResponse.ipo_transactions:type_name -> qubic.aggregation.general.v1.IpoBidTransactions
	5, // 3: qubic.aggregation.general.v1.GetIdentitiesBalancesResponse.balances:type_name -> qubic.aggregation.general.v1.IdentityBalance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_qubic_aggregation_general_v1_messages_proto_init() }
func file_qubic_aggregation_general_v1_messages_proto_init() {
	if File_qubic_aggregation_general_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qubic_aggregation_general_v1_messages_proto_rawDesc), len(file_qubic_aggregation_general_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qubic_aggregation_general_v1_messages_proto_goTypes,
		DependencyIndexes: file_qubic_aggregation_general_v1_messages_proto_depIdxs,
		MessageInfos:      file_qubic_aggregation_general_v1_messages_proto_msgTypes,
	}.Build()
	File_qubic_aggregation_general_v1_messages_proto = out.File
	file_qubic_aggregation_general_v1_messages_proto_goTypes = nil
	file_qubic_aggregation_general_v1_messages_proto_depIdxs = nil
}
