// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: qubic/aggregation/general/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregationGeneralService_GetCurrentIpoBids_FullMethodName     = "/qubic.aggregation.general.v1.AggregationGeneralService/GetCurrentIpoBids"
	AggregationGeneralService_GetIdentitiesBalances_FullMethodName = "/qubic.aggregation.general.v1.AggregationGeneralService/GetIdentitiesBalances"
)

// AggregationGeneralServiceClient is the client API for AggregationGeneralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregationGeneralServiceClient interface {
	GetCurrentIpoBids(ctx context.Context, in *GetCurrentIpoBidsRequest, opts ...grpc.CallOption) (*GetCurrentIpoBidsResponse, error)
	GetIdentitiesBalances(ctx context.Context, in *GetIdentitiesBalancesRequest, opts ...grpc.CallOption) (*GetIdentitiesBalancesResponse, error)
}

type aggregationGeneralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregationGeneralServiceClient(cc grpc.ClientConnInterface) AggregationGeneralServiceClient {
	return &aggregationGeneralServiceClient{cc}
}

func (c *aggregationGeneralServiceClient) GetCurrentIpoBids(ctx context.Context, in *GetCurrentIpoBidsRequest, opts ...grpc.CallOption) (*GetCurrentIpoBidsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentIpoBidsResponse)
	err := c.cc.Invoke(ctx, AggregationGeneralService_GetCurrentIpoBids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationGeneralServiceClient) GetIdentitiesBalances(ctx context.Context, in *GetIdentitiesBalancesRequest, opts ...grpc.CallOption) (*GetIdentitiesBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentitiesBalancesResponse)
	err := c.cc.Invoke(ctx, AggregationGeneralService_GetIdentitiesBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregationGeneralServiceServer is the server API for AggregationGeneralService service.
// All implementations must embed UnimplementedAggregationGeneralServiceServer
// for forward compatibility.
type AggregationGeneralServiceServer interface {
	GetCurrentIpoBids(context.Context, *GetCurrentIpoBidsRequest) (*GetCurrentIpoBidsResponse, error)
	GetIdentitiesBalances(context.Context, *GetIdentitiesBalancesRequest) (*GetIdentitiesBalancesResponse, error)
	mustEmbedUnimplementedAggregationGeneralServiceServer()
}

// UnimplementedAggregationGeneralServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregationGeneralServiceServer struct{}

func (UnimplementedAggregationGeneralServiceServer) GetCurrentIpoBids(context.Context, *GetCurrentIpoBidsRequest) (*GetCurrentIpoBidsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentIpoBids not implemented")
}
func (UnimplementedAggregationGeneralServiceServer) GetIdentitiesBalances(context.Context, *GetIdentitiesBalancesRequest) (*GetIdentitiesBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentitiesBalances not implemented")
}
func (UnimplementedAggregationGeneralServiceServer) mustEmbedUnimplementedAggregationGeneralServiceServer() {
}
func (UnimplementedAggregationGeneralServiceServer) testEmbeddedByValue() {}

// UnsafeAggregationGeneralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregationGeneralServiceServer will
// result in compilation errors.
type UnsafeAggregationGeneralServiceServer interface {
	mustEmbedUnimplementedAggregationGeneralServiceServer()
}

func RegisterAggregationGeneralServiceServer(s grpc.ServiceRegistrar, srv AggregationGeneralServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregationGeneralServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregationGeneralService_ServiceDesc, srv)
}

func _AggregationGeneralService_GetCurrentIpoBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentIpoBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationGeneralServiceServer).GetCurrentIpoBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationGeneralService_GetCurrentIpoBids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationGeneralServiceServer).GetCurrentIpoBids(ctx, req.(*GetCurrentIpoBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationGeneralService_GetIdentitiesBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentitiesBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationGeneralServiceServer).GetIdentitiesBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationGeneralService_GetIdentitiesBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationGeneralServiceServer).GetIdentitiesBalances(ctx, req.(*GetIdentitiesBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregationGeneralService_ServiceDesc is the grpc.ServiceDesc for AggregationGeneralService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregationGeneralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.aggregation.general.v1.AggregationGeneralService",
	HandlerType: (*AggregationGeneralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentIpoBids",
			Handler:    _AggregationGeneralService_GetCurrentIpoBids_Handler,
		},
		{
			MethodName: "GetIdentitiesBalances",
			Handler:    _AggregationGeneralService_GetIdentitiesBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qubic/aggregation/general/v1/service.proto",
}
