// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qubic/archive-query-service/v2/api/archive-query-service/v2 (interfaces: ArchiveQueryServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_query_service.go -package=mocks github.com/qubic/archive-query-service/v2/api/archive-query-service/v2 ArchiveQueryServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/qubic/archive-query-service/v2/api/archive-query-service/v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockArchiveQueryServiceClient is a mock of ArchiveQueryServiceClient interface.
type MockArchiveQueryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveQueryServiceClientMockRecorder
	isgomock struct{}
}

// MockArchiveQueryServiceClientMockRecorder is the mock recorder for MockArchiveQueryServiceClient.
type MockArchiveQueryServiceClientMockRecorder struct {
	mock *MockArchiveQueryServiceClient
}

// NewMockArchiveQueryServiceClient creates a new mock instance.
func NewMockArchiveQueryServiceClient(ctrl *gomock.Controller) *MockArchiveQueryServiceClient {
	mock := &MockArchiveQueryServiceClient{ctrl: ctrl}
	mock.recorder = &MockArchiveQueryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveQueryServiceClient) EXPECT() *MockArchiveQueryServiceClientMockRecorder {
	return m.recorder
}

// GetComputorsListsForEpoch mocks base method.
func (m *MockArchiveQueryServiceClient) GetComputorsListsForEpoch(ctx context.Context, in *api.GetComputorListsForEpochRequest, opts ...grpc.CallOption) (*api.GetComputorListsForEpochResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComputorsListsForEpoch", varargs...)
	ret0, _ := ret[0].(*api.GetComputorListsForEpochResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputorsListsForEpoch indicates an expected call of GetComputorsListsForEpoch.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetComputorsListsForEpoch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputorsListsForEpoch", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetComputorsListsForEpoch), varargs...)
}

// GetEvents mocks base method.
func (m *MockArchiveQueryServiceClient) GetEvents(ctx context.Context, in *api.GetEventsRequest, opts ...grpc.CallOption) (*api.GetEventsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEvents", varargs...)
	ret0, _ := ret[0].(*api.GetEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetEvents(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetEvents), varargs...)
}

// GetHealth mocks base method.
func (m *MockArchiveQueryServiceClient) GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.HealthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHealth", varargs...)
	ret0, _ := ret[0].(*api.HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHealth indicates an expected call of GetHealth.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetHealth(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealth", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetHealth), varargs...)
}

// GetLastProcessedTick mocks base method.
func (m *MockArchiveQueryServiceClient) GetLastProcessedTick(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.GetLastProcessedTickResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastProcessedTick", varargs...)
	ret0, _ := ret[0].(*api.GetLastProcessedTickResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastProcessedTick indicates an expected call of GetLastProcessedTick.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetLastProcessedTick(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastProcessedTick", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetLastProcessedTick), varargs...)
}

// GetProcessedTickIntervals mocks base method.
func (m *MockArchiveQueryServiceClient) GetProcessedTickIntervals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.GetProcessedTickIntervalsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProcessedTickIntervals", varargs...)
	ret0, _ := ret[0].(*api.GetProcessedTickIntervalsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessedTickIntervals indicates an expected call of GetProcessedTickIntervals.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetProcessedTickIntervals(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessedTickIntervals", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetProcessedTickIntervals), varargs...)
}

// GetTickData mocks base method.
func (m *MockArchiveQueryServiceClient) GetTickData(ctx context.Context, in *api.GetTickDataRequest, opts ...grpc.CallOption) (*api.GetTickDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTickData", varargs...)
	ret0, _ := ret[0].(*api.GetTickDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickData indicates an expected call of GetTickData.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetTickData(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickData", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetTickData), varargs...)
}

// GetTransactionByHash mocks base method.
func (m *MockArchiveQueryServiceClient) GetTransactionByHash(ctx context.Context, in *api.GetTransactionByHashRequest, opts ...grpc.CallOption) (*api.GetTransactionByHashResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionByHash", varargs...)
	ret0, _ := ret[0].(*api.GetTransactionByHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByHash indicates an expected call of GetTransactionByHash.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetTransactionByHash(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByHash", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetTransactionByHash), varargs...)
}

// GetTransactionsForIdentity mocks base method.
func (m *MockArchiveQueryServiceClient) GetTransactionsForIdentity(ctx context.Context, in *api.GetTransactionsForIdentityRequest, opts ...grpc.CallOption) (*api.GetTransactionsForIdentityResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionsForIdentity", varargs...)
	ret0, _ := ret[0].(*api.GetTransactionsForIdentityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsForIdentity indicates an expected call of GetTransactionsForIdentity.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetTransactionsForIdentity(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsForIdentity", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetTransactionsForIdentity), varargs...)
}

// GetTransactionsForTick mocks base method.
func (m *MockArchiveQueryServiceClient) GetTransactionsForTick(ctx context.Context, in *api.GetTransactionsForTickRequest, opts ...grpc.CallOption) (*api.GetTransactionsForTickResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionsForTick", varargs...)
	ret0, _ := ret[0].(*api.GetTransactionsForTickResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsForTick indicates an expected call of GetTransactionsForTick.
func (mr *MockArchiveQueryServiceClientMockRecorder) GetTransactionsForTick(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsForTick", reflect.TypeOf((*MockArchiveQueryServiceClient)(nil).GetTransactionsForTick), varargs...)
}
